/**
 * Demo data used as placeholders and initial values for the blog
 */

export const title = "Pak Blog.";

export const description = [
  {
    _key: "9f1a629887fd",
    _type: "block",
    children: [
      {
        _key: "4a58edd077880",
        _type: "span",
        marks: [],
        text: " A Blogging Website Generated By Pak Blog. ",
      },
      {
        _key: "4a58edd077881",
        _type: "span",
        marks: ["ec5b66c9b1e0"],
        text: " ",
      },
      {
        _key: "4a58edd077882",
        _type: "span",
        marks: [],
        text: " ",
      },
      {
        _key: "4a58edd077883",
        _type: "span",
        marks: ["1f8991913ea8"],
        text: " ",
      },
      {
        _key: "4a58edd077884",
        _type: "span",
        marks: [],
        text: "",
      },
    ],
   
    style: "normal",
  },
];

export const ogImageTitle = "A Next.js Blog with a Native Authoring Experience";
